### ISSUE TITLE
Compatibility Issue with `python-telegram-bot` v21+

### ISSUE THREAD

**Issue by robelasefa** [wiltonsr/ptb-pagination#1]
### Description:

I'm encountering a version conflict when installing `ptb_pagination` alongside the latest version of `python-telegram-bot` (v21.1.1).

`ptb_pagination` appears to have a dependency on an older version of `python-telegram-bot` (v13.x). This creates a conflict when I try to install both packages using `pip install -r requirements.txt`.

### Request:

Could you please investigate potential compatibility between `ptb_pagination` and newer versions of `python-telegram-bot`?

**Comment by wiltonsr** [comment]
Hello, @robelasefa 

> ptb_pagination appears to have a dependency on an older version of python-telegram-bot (v13.x).

`ptb_pagination` has a dependency on `python-telegram-bot>=13.6`. 

https://github.com/wiltonsr/ptb-pagination/blob/main/setup.py#L19-L21

Could you provide some more logs about your error? I can install `ptb-pagination` alongside `python-telegram-bot==21.1.1` without problems.

**Comment by wiltonsr** [comment]
It was closed due to inactivity. Please feel free to reopen if you need to.

**Comment by robelasefa** [comment]
> 
Hello everyone,

I'm writing to apologize for my previous comment on this issue. I've since realized that the error I was seeing when installing the ptb_pagination package was not due to the package itself, but rather to another package in my requirements.txt.
